### ISSUE TITLE
Slice Pattern Setup

### ISSUE THREAD

**Issue by JUNNNI** [michaeljota/zustand-entity-adapter#1]
@michaeljota thanks for this nice work.

It works well when creating different stores but is it possible to use it with Slices Pattern: https://zustand.docs.pmnd.rs/guides/slices-pattern ?

**Comment by michaeljota** [comment]
I think you can use the slice pattern with something like this:

```ts
// Create the entity adapter
const bearAdapter = createEntityAdapter<Bear, number>();

export const createBearSlice = (set) => ({
  ...bearAdapter.getState(),
  ...bearAdapter.getActions(set),
});

// Configure the entity selectors
const bearSelectors = bearAdapter.getSelectors();
```

Let me know if this helps!
