### ISSUE TITLE
computed values?

### ISSUE THREAD

**Issue by hmidmrii** [michaeljota/zustand-entity-adapter#2]
is there an efficient way to have computed values, I don't want to use custom hooks because it will cause each hook usage to have its own computations,
I looked over the code and I think implementing computed should be internally

**Comment by hmidmrii** [comment]
subscribing to the store and setting the computed value works as well but creates a sync issue, where there is a snapshot that have unmatched state with computed

**Comment by michaeljota** [comment]
I'm not sure what you mean by computed values. Can you provide a code example? Maybe you want to use a custom selector. This library provides selectors to select pieces of the entity store, but you can create your own if you need something else.

**Comment by hmidmrii** [comment]
Here's my entity:
```ts
export type Entity = {
  id: string;
  tree: Tree;
}
```
I want to derive a value from the tree to be the stringified version, like:
```ts
const useStore = create((_set, get) => ({
  tree: initialTree,
  stringifiedTree: computed(() => [get().tree], (tree) => stringifyTree(tree))
}))
```
so in the component I can do:
```tsx
const stringifiedTree = useStore(s => s.stringifiedTree());
```

**Comment by hmidmrii** [comment]
you can argue that I can use a custom hook, but the issue that is for each hook usage it would create its own version of the computation, which means when the tree is going to change, each usage for the hook would do its own stringifing.

**Comment by hmidmrii** [comment]
the issue with the standard computed that you need the entity id to select the correct state to add it to the dependencies of the computed

**Comment by hmidmrii** [comment]
so I did implement the following computed which works with entity adapter but it's clunky a bit:
```ts
export type EqualityFn<T> = (a: T, b: T) => boolean;
export type CacheKey = string | number;

const defaultEqualityFn = (a: any, b: any): boolean => a.length === b.length && a.every((v, i) => Object.is(v, b[i]));

export const computed = <
  const TDepsArgs extends readonly unknown[] = unknown[],
  const TDeps extends readonly unknown[] = unknown[],
  TResult = unknown,
>(
  depsFn: (...args: TDepsArgs) => TDeps,
  computeFn: (...deps: TDeps) => TResult,
  cacheKey: (...args: TDepsArgs) => CacheKey = (...deps) => JSON.stringify(deps),
  equalityFn: EqualityFn<TDeps> = defaultEqualityFn
) => {
  const cachedDeps: Record<CacheKey, TDeps> = {};
  const cachedResult: Record<CacheKey, TResult> = {};

  return (...args: TDepsArgs): TResult => {
    const deps = depsFn(...args);

    const key = cacheKey(...args);

    if (cachedDeps[key] === undefined || !equalityFn(cachedDeps[key], deps)) {
      cachedDeps[key] = deps;
      cachedResult[key] = computeFn(...deps);
    }

    return cachedResult[key];
  };
};
```

which can be used as follows:
```ts
const store = createEntityStore<Entity, {}, ShortcodeStoreExtraAction>(
  {},
  initialState,
  (_set, get) => ({
    stringifiedTree: computed(
      (id: EntityId) => [get().entities[id].tree],
      (tree) => strinfigyTree(tree)
    ),

```

and in the component:
```ts
const stringifiedTree = useStore(store, s => s.stringifiedTree(id));
```

**Comment by hmidmrii** [comment]
you can see, this computed solve the problem, but because it's not baked into the entity adapter implementation, it feels like a hack not like a respected solution

**Comment by hmidmrii** [comment]
BTW I found this computed function somewhere on the web but did the modification to make it work with entity adapter, so it's not fully my invention.

**Comment by hmidmrii** [comment]
BTW thanks for the great work on this lib, I think it's missing tests, tell me if want a hand on it

**Comment by michaeljota** [comment]
I think it's a great solution. However, I don't see how this library can benefit from it because it's outside the scope of this library how to memoize your state. I could suggest you to use a custom hook instead, using a useMemo.

Something like:

```ts
const useStore = create((_set, get) => ({
  tree: initialTree,
}))
```

```ts
const useStringifiedTree = () => {
  const tree = useStore((state) => state.tree);
  return useMemo(() => stringifyTree(tree), [tree]);
}
```

That will memoize the function and will share that state with other components.

I'll close this since the request is outside of the scope of this library as I mentioned. I'm glad you find this helpful.

**Comment by hmidmrii** [comment]
@michaeljota as I mentioned before, each usage of this hook will have it's own memorization, which makes it bad for both performance and memory, but it's fine as I mentioned the previous computed solved the problem for me

**Comment by michaeljota** [comment]
No, the memoization will be shared as part of React state management, if you are using React.
